"""
CyperMark — Система локализации / Localization
Поддерживает 15 языков с флагами
"""

# ─── Список доступных языков (код → название + флаг) ──────────
LANG_NAMES = {
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
    "de": "🇩🇪 Deutsch",
    "fr": "🇫🇷 Français",
    "es": "🇪🇸 Español",
    "it": "🇮🇹 Italiano",
    "pt": "🇧🇷 Português",
    "zh": "🇨🇳 中文",
    "ja": "🇯🇵 日本語",
    "ko": "🇰🇷 한국어",
    "ar": "🇸🇦 العربية",
    "tr": "🇹🇷 Türkçe",
    "pl": "🇵🇱 Polski",
    "nl": "🇳🇱 Nederlands",
    "sv": "🇸🇪 Svenska",
}

LANGUAGES: dict[str, dict[str, str]] = {
    # ═══════════════════════════════════════════════════════════
    #  РУССКИЙ
    # ═══════════════════════════════════════════════════════════
    "ru": {
        "app.title": "CyperMark v2 — Пакетный водяной знак",

        "files.title": "📁 Файлы",
        "files.add": "+ Добавить файлы",
        "files.add_folder": "+ Добавить папку",
        "files.clear": "✕ Очистить список",
        "files.none": "Нет файлов",
        "files.count": "Файлов: {n}",
        "files.select_images": "Выберите изображения",
        "files.select_folder": "Выберите папку с изображениями",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Все файлы",
        "files.cleared": "Список файлов очищен",
        "files.no_preview": "Нет файлов для предпросмотра",
        "files.and_more": "... и ещё {n} файлов",

        "settings.title": "⚙️ Настройки",

        "mode.title": "🎨 Тип водяного знака",
        "mode.text": "Текст",
        "mode.logo": "Логотип",

        "text.label": "✏️ Текст",
        "text.placeholder": "© CyperMark",
        "text.font": "Шрифт",
        "text.font_size": "Размер шрифта",
        "text.color": "Цвет шрифта",

        "stroke.title": "✏️ Обводка текста",
        "stroke.width": "Толщина",
        "stroke.color": "Цвет обводки",

        "logo.title": "🖼️ Логотип",
        "logo.select": "🖼️ Выбрать PNG",
        "logo.not_selected": "Не выбран",
        "logo.select_title": "Выберите логотип",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Ошибка: не выбран логотип",

        "position.title": "📍 Позиция",
        "pos.top_left": "Вверху слева",
        "pos.top_center": "Вверху центр",
        "pos.top_right": "Вверху справа",
        "pos.center": "Центр",
        "pos.bottom_left": "Внизу слева",
        "pos.bottom_center": "Внизу центр",
        "pos.bottom_right": "Внизу справа",
        "pos.tile": "Замостить",

        "opacity": "Прозрачность",
        "rotation": "Поворот (°)",

        "ai.title": "🤖 AI Auto-Placement",
        "ai.label": "Свободная область",

        "format.title": "💾 Выходной формат",
        "format.quality": "Качество (1-100)",

        "output.folder": "📥 Выходная папка",
        "output.select": "📁 Выбрать папку",
        "output.not_selected": "Не выбрана",

        "suffix.label": "🏷️ Суффикс файла",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Сохранить пресет",
        "preset.load": "📂 Загрузить пресет",
        "preset.reset": "↺ Сбросить настройки",
        "preset.save_title": "Сохранить пресет",
        "preset.load_title": "Загрузить пресет",
        "preset.saved": "Пресет сохранён: {name}",
        "preset.loaded": "Пресет загружен: {name}",
        "preset.reset_done": "Настройки сброшены",

        "preview.title": "🔍 Предпросмотр",

        "zoom.fit": "Fit",

        "status.ready": "Готов",
        "status.processing": "🚀 Запуск обработки...",
        "status.completed": "✅ Готово! Обработано {n} файлов",
        "status.error": "Ошибка: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 ЗАПУСТИТЬ",
        "btn.running": "⏳ ОБРАБОТКА...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Спасибо за поддержку!",

        "msg.no_files": "Ошибка: нет файлов для обработки",
        "msg.no_output": "Ошибка: не выбрана выходная папка",
        "msg.logo_required": "Ошибка: не выбран логотип",
        "msg.preview_error": "Ошибка превью: {e}",
        "msg.startup": "CyperMark v2 готов к работе. Добавьте изображения.",
        "msg.logo_loaded": "Логотип: {path}",
        "msg.files_added": "Добавлено {n} файлов",
        "msg.folder_added": "Добавлена папка: {name} ({n} изображений)",
        "msg.output_selected": "Выходная папка: {path}",
        "msg.saved_to": "✅ Готово! Сохранено в: {path}",

        "color.pick_font": "Цвет шрифта",
        "color.pick_stroke": "Цвет обводки",

        "about.title": "ℹ️ О программе",
        "about.name": "⚡ CyperMark",
        "about.desc": "Пакетное наложение водяных знаков",
        "about.subdesc": "AI-защита ваших изображений",
        "about.version": "v2.0",
        "about.license": "Лицензия: MIT",
        "about.close": "Закрыть",
    },

    # ═══════════════════════════════════════════════════════════
    #  ENGLISH
    # ═══════════════════════════════════════════════════════════
    "en": {
        "app.title": "CyperMark v2 — Batch Watermark Tool",

        "files.title": "📁 Files",
        "files.add": "+ Add Files",
        "files.add_folder": "+ Add Folder",
        "files.clear": "✕ Clear List",
        "files.none": "No files",
        "files.count": "Files: {n}",
        "files.select_images": "Select images",
        "files.select_folder": "Select folder with images",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "All files",
        "files.cleared": "File list cleared",
        "files.no_preview": "No files for preview",
        "files.and_more": "... and {n} more files",

        "settings.title": "⚙️ Settings",

        "mode.title": "🎨 Watermark Type",
        "mode.text": "Text",
        "mode.logo": "Logo",

        "text.label": "✏️ Text",
        "text.placeholder": "© CyperMark",
        "text.font": "Font",
        "text.font_size": "Font Size",
        "text.color": "Font Color",

        "stroke.title": "✏️ Text Stroke",
        "stroke.width": "Width",
        "stroke.color": "Stroke Color",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Select PNG",
        "logo.not_selected": "Not selected",
        "logo.select_title": "Select logo image",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Error: no logo selected",

        "position.title": "📍 Position",
        "pos.top_left": "Top Left",
        "pos.top_center": "Top Center",
        "pos.top_right": "Top Right",
        "pos.center": "Center",
        "pos.bottom_left": "Bottom Left",
        "pos.bottom_center": "Bottom Center",
        "pos.bottom_right": "Bottom Right",
        "pos.tile": "Tile",

        "opacity": "Opacity",
        "rotation": "Rotation (°)",

        "ai.title": "🤖 AI Auto-Placement",
        "ai.label": "Free Area",

        "format.title": "💾 Output Format",
        "format.quality": "Quality (1-100)",

        "output.folder": "📥 Output Folder",
        "output.select": "📁 Select Folder",
        "output.not_selected": "Not selected",

        "suffix.label": "🏷️ File Suffix",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Save Preset",
        "preset.load": "📂 Load Preset",
        "preset.reset": "↺ Reset Settings",
        "preset.save_title": "Save Preset",
        "preset.load_title": "Load Preset",
        "preset.saved": "Preset saved: {name}",
        "preset.loaded": "Preset loaded: {name}",
        "preset.reset_done": "Settings reset",

        "preview.title": "🔍 Preview",

        "zoom.fit": "Fit",

        "status.ready": "Ready",
        "status.processing": "🚀 Processing...",
        "status.completed": "✅ Done! {n} files processed",
        "status.error": "Error: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 START",
        "btn.running": "⏳ PROCESSING...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Thanks for your support!",

        "msg.no_files": "Error: no files to process",
        "msg.no_output": "Error: no output folder selected",
        "msg.logo_required": "Error: no logo selected",
        "msg.preview_error": "Preview error: {e}",
        "msg.startup": "CyperMark v2 ready. Add images to start.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} files added",
        "msg.folder_added": "Folder added: {name} ({n} images)",
        "msg.output_selected": "Output folder: {path}",
        "msg.saved_to": "✅ Done! Saved to: {path}",

        "color.pick_font": "Font Color",
        "color.pick_stroke": "Stroke Color",

        "about.title": "ℹ️ About",
        "about.name": "⚡ CyperMark",
        "about.desc": "Batch Watermark Tool",
        "about.subdesc": "AI-powered image protection",
        "about.version": "v2.0",
        "about.license": "License: MIT",
        "about.close": "Close",
    },

    # ═══════════════════════════════════════════════════════════
    #  DEUTSCH
    # ═══════════════════════════════════════════════════════════
    "de": {
        "app.title": "CyperMark v2 — Batch-Wasserzeichen",

        "files.title": "📁 Dateien",
        "files.add": "+ Dateien hinzufügen",
        "files.add_folder": "+ Ordner hinzufügen",
        "files.clear": "✕ Liste leeren",
        "files.none": "Keine Dateien",
        "files.count": "Dateien: {n}",
        "files.select_images": "Bilder auswählen",
        "files.select_folder": "Ordner mit Bildern auswählen",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Alle Dateien",
        "files.cleared": "Dateiliste geleert",
        "files.no_preview": "Keine Dateien für Vorschau",
        "files.and_more": "... und {n} weitere Dateien",

        "settings.title": "⚙️ Einstellungen",
        "mode.title": "🎨 Wasserzeichen-Typ",
        "mode.text": "Text",
        "mode.logo": "Logo",

        "text.label": "✏️ Text",
        "text.placeholder": "© CyperMark",
        "text.font": "Schriftart",
        "text.font_size": "Schriftgröße",
        "text.color": "Schriftfarbe",

        "stroke.title": "✏️ Textkontur",
        "stroke.width": "Breite",
        "stroke.color": "Konturfarbe",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ PNG auswählen",
        "logo.not_selected": "Nicht ausgewählt",
        "logo.select_title": "Logo-Bild auswählen",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Fehler: kein Logo ausgewählt",

        "position.title": "📍 Position",
        "pos.top_left": "Oben links",
        "pos.top_center": "Oben Mitte",
        "pos.top_right": "Oben rechts",
        "pos.center": "Mitte",
        "pos.bottom_left": "Unten links",
        "pos.bottom_center": "Unten Mitte",
        "pos.bottom_right": "Unten rechts",
        "pos.tile": "Kacheln",

        "opacity": "Deckkraft",
        "rotation": "Drehung (°)",

        "ai.title": "🤖 AI Auto-Placement",
        "ai.label": "Freie Fläche",

        "format.title": "💾 Ausgabeformat",
        "format.quality": "Qualität (1-100)",

        "output.folder": "📥 Ausgabeordner",
        "output.select": "📁 Ordner wählen",
        "output.not_selected": "Nicht gewählt",

        "suffix.label": "🏷️ Dateisuffix",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Preset speichern",
        "preset.load": "📂 Preset laden",
        "preset.reset": "↺ Zurücksetzen",
        "preset.save_title": "Preset speichern",
        "preset.load_title": "Preset laden",
        "preset.saved": "Preset gespeichert: {name}",
        "preset.loaded": "Preset geladen: {name}",
        "preset.reset_done": "Einstellungen zurückgesetzt",

        "preview.title": "🔍 Vorschau",
        "zoom.fit": "Anpassen",

        "status.ready": "Bereit",
        "status.processing": "🚀 Verarbeitung...",
        "status.completed": "✅ Fertig! {n} Dateien verarbeitet",
        "status.error": "Fehler: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 START",
        "btn.running": "⏳ VERARBEITUNG...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Danke für deine Unterstützung!",

        "msg.no_files": "Fehler: keine Dateien zum Verarbeiten",
        "msg.no_output": "Fehler: kein Ausgabeordner gewählt",
        "msg.logo_required": "Fehler: kein Logo ausgewählt",
        "msg.preview_error": "Vorschaufehler: {e}",
        "msg.startup": "CyperMark v2 bereit. Bilder hinzufügen.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} Dateien hinzugefügt",
        "msg.folder_added": "Ordner hinzugefügt: {name} ({n} Bilder)",
        "msg.output_selected": "Ausgabeordner: {path}",
        "msg.saved_to": "✅ Fertig! Gespeichert in: {path}",

        "color.pick_font": "Schriftfarbe",
        "color.pick_stroke": "Konturfarbe",

        "about.title": "ℹ️ Über",
        "about.name": "⚡ CyperMark",
        "about.desc": "Batch-Wasserzeichen-Werkzeug",
        "about.subdesc": "KI-gestützter Bilderschutz",
        "about.version": "v2.0",
        "about.license": "Lizenz: MIT",
        "about.close": "Schließen",
    },

    # ═══════════════════════════════════════════════════════════
    #  FRANÇAIS
    # ═══════════════════════════════════════════════════════════
    "fr": {
        "app.title": "CyperMark v2 — Filigrane par lot",

        "files.title": "📁 Fichiers",
        "files.add": "+ Ajouter des fichiers",
        "files.add_folder": "+ Ajouter un dossier",
        "files.clear": "✕ Vider la liste",
        "files.none": "Aucun fichier",
        "files.count": "Fichiers : {n}",
        "files.select_images": "Sélectionner des images",
        "files.select_folder": "Sélectionner un dossier d'images",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Tous les fichiers",
        "files.cleared": "Liste de fichiers vidée",
        "files.no_preview": "Aucun fichier pour l'aperçu",
        "files.and_more": "... et {n} autres fichiers",

        "settings.title": "⚙️ Paramètres",
        "mode.title": "🎨 Type de filigrane",
        "mode.text": "Texte",
        "mode.logo": "Logo",

        "text.label": "✏️ Texte",
        "text.placeholder": "© CyperMark",
        "text.font": "Police",
        "text.font_size": "Taille de police",
        "text.color": "Couleur du texte",

        "stroke.title": "✏️ Contour du texte",
        "stroke.width": "Épaisseur",
        "stroke.color": "Couleur du contour",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Sélectionner PNG",
        "logo.not_selected": "Non sélectionné",
        "logo.select_title": "Sélectionner l'image du logo",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Erreur : aucun logo sélectionné",

        "position.title": "📍 Position",
        "pos.top_left": "En haut à gauche",
        "pos.top_center": "En haut au centre",
        "pos.top_right": "En haut à droite",
        "pos.center": "Centre",
        "pos.bottom_left": "En bas à gauche",
        "pos.bottom_center": "En bas au centre",
        "pos.bottom_right": "En bas à droite",
        "pos.tile": "Mosaïque",

        "opacity": "Opacité",
        "rotation": "Rotation (°)",

        "ai.title": "🤖 AI Auto-Placement",
        "ai.label": "Zone libre",

        "format.title": "💾 Format de sortie",
        "format.quality": "Qualité (1-100)",

        "output.folder": "📥 Dossier de sortie",
        "output.select": "📁 Choisir le dossier",
        "output.not_selected": "Non sélectionné",

        "suffix.label": "🏷️ Suffixe de fichier",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Enregistrer le préréglage",
        "preset.load": "📂 Charger le préréglage",
        "preset.reset": "↺ Réinitialiser",
        "preset.save_title": "Enregistrer le préréglage",
        "preset.load_title": "Charger le préréglage",
        "preset.saved": "Préréglage enregistré : {name}",
        "preset.loaded": "Préréglage chargé : {name}",
        "preset.reset_done": "Paramètres réinitialisés",

        "preview.title": "🔍 Aperçu",
        "zoom.fit": "Ajuster",

        "status.ready": "Prêt",
        "status.processing": "🚀 Traitement...",
        "status.completed": "✅ Terminé ! {n} fichiers traités",
        "status.error": "Erreur : {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 DÉMARRER",
        "btn.running": "⏳ TRAITEMENT...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Merci pour votre soutien !",

        "msg.no_files": "Erreur : aucun fichier à traiter",
        "msg.no_output": "Erreur : aucun dossier de sortie sélectionné",
        "msg.logo_required": "Erreur : aucun logo sélectionné",
        "msg.preview_error": "Erreur d'aperçu : {e}",
        "msg.startup": "CyperMark v2 prêt. Ajoutez des images.",
        "msg.logo_loaded": "Logo : {path}",
        "msg.files_added": "{n} fichiers ajoutés",
        "msg.folder_added": "Dossier ajouté : {name} ({n} images)",
        "msg.output_selected": "Dossier de sortie : {path}",
        "msg.saved_to": "✅ Terminé ! Enregistré dans : {path}",

        "color.pick_font": "Couleur du texte",
        "color.pick_stroke": "Couleur du contour",

        "about.title": "ℹ️ À propos",
        "about.name": "⚡ CyperMark",
        "about.desc": "Filigrane par lot",
        "about.subdesc": "Protection d'images par IA",
        "about.version": "v2.0",
        "about.license": "Licence : MIT",
        "about.close": "Fermer",
    },

    # ═══════════════════════════════════════════════════════════
    #  ESPAÑOL
    # ═══════════════════════════════════════════════════════════
    "es": {
        "app.title": "CyperMark v2 — Marca de agua por lotes",

        "files.title": "📁 Archivos",
        "files.add": "+ Añadir archivos",
        "files.add_folder": "+ Añadir carpeta",
        "files.clear": "✕ Limpiar lista",
        "files.none": "Sin archivos",
        "files.count": "Archivos: {n}",
        "files.select_images": "Seleccionar imágenes",
        "files.select_folder": "Seleccionar carpeta con imágenes",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Todos los archivos",
        "files.cleared": "Lista de archivos limpiada",
        "files.no_preview": "Sin archivos para previsualizar",
        "files.and_more": "... y {n} archivos más",

        "settings.title": "⚙️ Configuración",
        "mode.title": "🎨 Tipo de marca de agua",
        "mode.text": "Texto",
        "mode.logo": "Logo",

        "text.label": "✏️ Texto",
        "text.placeholder": "© CyperMark",
        "text.font": "Fuente",
        "text.font_size": "Tamaño de fuente",
        "text.color": "Color del texto",

        "stroke.title": "✏️ Contorno del texto",
        "stroke.width": "Grosor",
        "stroke.color": "Color del contorno",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Seleccionar PNG",
        "logo.not_selected": "No seleccionado",
        "logo.select_title": "Seleccionar imagen del logo",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Error: no se seleccionó logo",

        "position.title": "📍 Posición",
        "pos.top_left": "Arriba izquierda",
        "pos.top_center": "Arriba centro",
        "pos.top_right": "Arriba derecha",
        "pos.center": "Centro",
        "pos.bottom_left": "Abajo izquierda",
        "pos.bottom_center": "Abajo centro",
        "pos.bottom_right": "Abajo derecha",
        "pos.tile": "Mosaico",

        "opacity": "Opacidad",
        "rotation": "Rotación (°)",

        "ai.title": "🤖 AI Auto-Placement",
        "ai.label": "Área libre",

        "format.title": "💾 Formato de salida",
        "format.quality": "Calidad (1-100)",

        "output.folder": "📥 Carpeta de salida",
        "output.select": "📁 Seleccionar carpeta",
        "output.not_selected": "No seleccionada",

        "suffix.label": "🏷️ Sufijo del archivo",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Guardar preajuste",
        "preset.load": "📂 Cargar preajuste",
        "preset.reset": "↺ Restablecer",
        "preset.save_title": "Guardar preajuste",
        "preset.load_title": "Cargar preajuste",
        "preset.saved": "Preajuste guardado: {name}",
        "preset.loaded": "Preajuste cargado: {name}",
        "preset.reset_done": "Configuración restablecida",

        "preview.title": "🔍 Vista previa",
        "zoom.fit": "Ajustar",

        "status.ready": "Listo",
        "status.processing": "🚀 Procesando...",
        "status.completed": "✅ ¡Listo! {n} archivos procesados",
        "status.error": "Error: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 INICIAR",
        "btn.running": "⏳ PROCESANDO...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ ¡Gracias por tu apoyo!",

        "msg.no_files": "Error: no hay archivos para procesar",
        "msg.no_output": "Error: no se seleccionó carpeta de salida",
        "msg.logo_required": "Error: no se seleccionó logo",
        "msg.preview_error": "Error de previsualización: {e}",
        "msg.startup": "CyperMark v2 listo. Añade imágenes.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} archivos añadidos",
        "msg.folder_added": "Carpeta añadida: {name} ({n} imágenes)",
        "msg.output_selected": "Carpeta de salida: {path}",
        "msg.saved_to": "✅ ¡Listo! Guardado en: {path}",

        "color.pick_font": "Color del texto",
        "color.pick_stroke": "Color del contorno",

        "about.title": "ℹ️ Acerca de",
        "about.name": "⚡ CyperMark",
        "about.desc": "Marca de agua por lotes",
        "about.subdesc": "Protección de imágenes con IA",
        "about.version": "v2.0",
        "about.license": "Licencia: MIT",
        "about.close": "Cerrar",
    },

    # ═══════════════════════════════════════════════════════════
    #  ITALIANO
    # ═══════════════════════════════════════════════════════════
    "it": {
        "app.title": "CyperMark v2 — Filigrana batch",

        "files.title": "📁 File",
        "files.add": "+ Aggiungi file",
        "files.add_folder": "+ Aggiungi cartella",
        "files.clear": "✕ Pulisci lista",
        "files.none": "Nessun file",
        "files.count": "File: {n}",
        "files.select_images": "Seleziona immagini",
        "files.select_folder": "Seleziona cartella con immagini",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Tutti i file",
        "files.cleared": "Lista file pulita",
        "files.no_preview": "Nessun file per l'anteprima",
        "files.and_more": "... e altri {n} file",

        "settings.title": "⚙️ Impostazioni",
        "mode.title": "🎨 Tipo di filigrana",
        "mode.text": "Testo",
        "mode.logo": "Logo",

        "text.label": "✏️ Testo",
        "text.placeholder": "© CyperMark",
        "text.font": "Carattere",
        "text.font_size": "Dimensione carattere",
        "text.color": "Colore del testo",

        "stroke.title": "✏️ Contorno testo",
        "stroke.width": "Spessore",
        "stroke.color": "Colore contorno",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Seleziona PNG",
        "logo.not_selected": "Non selezionato",
        "logo.select_title": "Seleziona immagine logo",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Errore: nessun logo selezionato",

        "position.title": "📍 Posizione",
        "pos.top_left": "In alto a sinistra",
        "pos.top_center": "In alto al centro",
        "pos.top_right": "In alto a destra",
        "pos.center": "Centro",
        "pos.bottom_left": "In basso a sinistra",
        "pos.bottom_center": "In basso al centro",
        "pos.bottom_right": "In basso a destra",
        "pos.tile": "Affianca",

        "opacity": "Opacità",
        "rotation": "Rotazione (°)",

        "ai.title": "🤖 AI Auto-Posizionamento",
        "ai.label": "Area libera",

        "format.title": "💾 Formato di output",
        "format.quality": "Qualità (1-100)",

        "output.folder": "📥 Cartella di output",
        "output.select": "📁 Seleziona cartella",
        "output.not_selected": "Non selezionata",

        "suffix.label": "🏷️ Suffisso file",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Salva preset",
        "preset.load": "📂 Carica preset",
        "preset.reset": "↺ Ripristina",
        "preset.save_title": "Salva preset",
        "preset.load_title": "Carica preset",
        "preset.saved": "Preset salvato: {name}",
        "preset.loaded": "Preset caricato: {name}",
        "preset.reset_done": "Impostazioni ripristinate",

        "preview.title": "🔍 Anteprima",
        "zoom.fit": "Adatta",

        "status.ready": "Pronto",
        "status.processing": "🚀 Elaborazione...",
        "status.completed": "✅ Fatto! {n} file elaborati",
        "status.error": "Errore: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 AVVIA",
        "btn.running": "⏳ ELABORAZIONE...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Grazie per il supporto!",

        "msg.no_files": "Errore: nessun file da elaborare",
        "msg.no_output": "Errore: nessuna cartella di output selezionata",
        "msg.logo_required": "Errore: nessun logo selezionato",
        "msg.preview_error": "Errore anteprima: {e}",
        "msg.startup": "CyperMark v2 pronto. Aggiungi immagini.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} file aggiunti",
        "msg.folder_added": "Cartella aggiunta: {name} ({n} immagini)",
        "msg.output_selected": "Cartella di output: {path}",
        "msg.saved_to": "✅ Fatto! Salvato in: {path}",

        "color.pick_font": "Colore del testo",
        "color.pick_stroke": "Colore contorno",

        "about.title": "ℹ️ Informazioni",
        "about.name": "⚡ CyperMark",
        "about.desc": "Filigrana batch",
        "about.subdesc": "Protezione immagini con IA",
        "about.version": "v2.0",
        "about.license": "Licenza: MIT",
        "about.close": "Chiudi",
    },

    # ═══════════════════════════════════════════════════════════
    #  PORTUGUÊS
    # ═══════════════════════════════════════════════════════════
    "pt": {
        "app.title": "CyperMark v2 — Marca d'água em lote",

        "files.title": "📁 Arquivos",
        "files.add": "+ Adicionar arquivos",
        "files.add_folder": "+ Adicionar pasta",
        "files.clear": "✕ Limpar lista",
        "files.none": "Nenhum arquivo",
        "files.count": "Arquivos: {n}",
        "files.select_images": "Selecionar imagens",
        "files.select_folder": "Selecionar pasta com imagens",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Todos os arquivos",
        "files.cleared": "Lista de arquivos limpa",
        "files.no_preview": "Nenhum arquivo para pré-visualizar",
        "files.and_more": "... e mais {n} arquivos",

        "settings.title": "⚙️ Configurações",
        "mode.title": "🎨 Tipo de marca d'água",
        "mode.text": "Texto",
        "mode.logo": "Logo",

        "text.label": "✏️ Texto",
        "text.placeholder": "© CyperMark",
        "text.font": "Fonte",
        "text.font_size": "Tamanho da fonte",
        "text.color": "Cor do texto",

        "stroke.title": "✏️ Contorno do texto",
        "stroke.width": "Espessura",
        "stroke.color": "Cor do contorno",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Selecionar PNG",
        "logo.not_selected": "Não selecionado",
        "logo.select_title": "Selecionar imagem do logo",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Erro: nenhum logo selecionado",

        "position.title": "📍 Posição",
        "pos.top_left": "Superior esquerdo",
        "pos.top_center": "Superior centro",
        "pos.top_right": "Superior direito",
        "pos.center": "Centro",
        "pos.bottom_left": "Inferior esquerdo",
        "pos.bottom_center": "Inferior centro",
        "pos.bottom_right": "Inferior direito",
        "pos.tile": "Ladrilho",

        "opacity": "Opacidade",
        "rotation": "Rotação (°)",

        "ai.title": "🤖 AI Auto-Posicionamento",
        "ai.label": "Área livre",

        "format.title": "💾 Formato de saída",
        "format.quality": "Qualidade (1-100)",

        "output.folder": "📥 Pasta de saída",
        "output.select": "📁 Selecionar pasta",
        "output.not_selected": "Não selecionada",

        "suffix.label": "🏷️ Sufixo do arquivo",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Salvar predefinição",
        "preset.load": "📂 Carregar predefinição",
        "preset.reset": "↺ Redefinir",
        "preset.save_title": "Salvar predefinição",
        "preset.load_title": "Carregar predefinição",
        "preset.saved": "Predefinição salva: {name}",
        "preset.loaded": "Predefinição carregada: {name}",
        "preset.reset_done": "Configurações redefinidas",

        "preview.title": "🔍 Pré-visualização",
        "zoom.fit": "Ajustar",

        "status.ready": "Pronto",
        "status.processing": "🚀 Processando...",
        "status.completed": "✅ Concluído! {n} arquivos processados",
        "status.error": "Erro: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 INICIAR",
        "btn.running": "⏳ PROCESSANDO...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Obrigado pelo apoio!",

        "msg.no_files": "Erro: nenhum arquivo para processar",
        "msg.no_output": "Erro: nenhuma pasta de saída selecionada",
        "msg.logo_required": "Erro: nenhum logo selecionado",
        "msg.preview_error": "Erro de pré-visualização: {e}",
        "msg.startup": "CyperMark v2 pronto. Adicione imagens.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} arquivos adicionados",
        "msg.folder_added": "Pasta adicionada: {name} ({n} imagens)",
        "msg.output_selected": "Pasta de saída: {path}",
        "msg.saved_to": "✅ Concluído! Salvo em: {path}",

        "color.pick_font": "Cor do texto",
        "color.pick_stroke": "Cor do contorno",

        "about.title": "ℹ️ Sobre",
        "about.name": "⚡ CyperMark",
        "about.desc": "Marca d'água em lote",
        "about.subdesc": "Proteção de imagens com IA",
        "about.version": "v2.0",
        "about.license": "Licença: MIT",
        "about.close": "Fechar",
    },

    # ═══════════════════════════════════════════════════════════
    #  中文 (Упрощённый китайский)
    # ═══════════════════════════════════════════════════════════
    "zh": {
        "app.title": "CyperMark v2 — 批量水印工具",

        "files.title": "📁 文件",
        "files.add": "+ 添加文件",
        "files.add_folder": "+ 添加文件夹",
        "files.clear": "✕ 清空列表",
        "files.none": "没有文件",
        "files.count": "文件: {n}",
        "files.select_images": "选择图片",
        "files.select_folder": "选择包含图片的文件夹",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "所有文件",
        "files.cleared": "文件列表已清空",
        "files.no_preview": "没有文件可预览",
        "files.and_more": "... 还有 {n} 个文件",

        "settings.title": "⚙️ 设置",
        "mode.title": "🎨 水印类型",
        "mode.text": "文字",
        "mode.logo": "标志",

        "text.label": "✏️ 文字",
        "text.placeholder": "© CyperMark",
        "text.font": "字体",
        "text.font_size": "字号",
        "text.color": "字体颜色",

        "stroke.title": "✏️ 文字描边",
        "stroke.width": "宽度",
        "stroke.color": "描边颜色",

        "logo.title": "🖼️ 标志",
        "logo.select": "🖼️ 选择PNG",
        "logo.not_selected": "未选择",
        "logo.select_title": "选择标志图片",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "错误：未选择标志",

        "position.title": "📍 位置",
        "pos.top_left": "左上",
        "pos.top_center": "上中",
        "pos.top_right": "右上",
        "pos.center": "居中",
        "pos.bottom_left": "左下",
        "pos.bottom_center": "下中",
        "pos.bottom_right": "右下",
        "pos.tile": "平铺",

        "opacity": "不透明度",
        "rotation": "旋转 (°)",

        "ai.title": "🤖 AI 自动放置",
        "ai.label": "自由区域",

        "format.title": "💾 输出格式",
        "format.quality": "质量 (1-100)",

        "output.folder": "📥 输出文件夹",
        "output.select": "📁 选择文件夹",
        "output.not_selected": "未选择",

        "suffix.label": "🏷️ 文件后缀",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 保存预设",
        "preset.load": "📂 加载预设",
        "preset.reset": "↺ 重置设置",
        "preset.save_title": "保存预设",
        "preset.load_title": "加载预设",
        "preset.saved": "预设已保存: {name}",
        "preset.loaded": "预设已加载: {name}",
        "preset.reset_done": "设置已重置",

        "preview.title": "🔍 预览",
        "zoom.fit": "适应",

        "status.ready": "就绪",
        "status.processing": "🚀 处理中...",
        "status.completed": "✅ 完成！已处理 {n} 个文件",
        "status.error": "错误: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 开始",
        "btn.running": "⏳ 处理中...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ 感谢您的支持！",

        "msg.no_files": "错误：没有文件可处理",
        "msg.no_output": "错误：未选择输出文件夹",
        "msg.logo_required": "错误：未选择标志",
        "msg.preview_error": "预览错误: {e}",
        "msg.startup": "CyperMark v2 就绪。请添加图片。",
        "msg.logo_loaded": "标志: {path}",
        "msg.files_added": "已添加 {n} 个文件",
        "msg.folder_added": "已添加文件夹: {name} ({n} 张图片)",
        "msg.output_selected": "输出文件夹: {path}",
        "msg.saved_to": "✅ 完成！保存至: {path}",

        "color.pick_font": "字体颜色",
        "color.pick_stroke": "描边颜色",

        "about.title": "ℹ️ 关于",
        "about.name": "⚡ CyperMark",
        "about.desc": "批量水印工具",
        "about.subdesc": "AI 图像保护",
        "about.version": "v2.0",
        "about.license": "许可证: MIT",
        "about.close": "关闭",
    },

    # ═══════════════════════════════════════════════════════════
    #  日本語
    # ═══════════════════════════════════════════════════════════
    "ja": {
        "app.title": "CyperMark v2 — バッチ透かしツール",

        "files.title": "📁 ファイル",
        "files.add": "+ ファイルを追加",
        "files.add_folder": "+ フォルダを追加",
        "files.clear": "✕ リストをクリア",
        "files.none": "ファイルがありません",
        "files.count": "ファイル: {n}",
        "files.select_images": "画像を選択",
        "files.select_folder": "画像フォルダを選択",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "すべてのファイル",
        "files.cleared": "ファイルリストをクリアしました",
        "files.no_preview": "プレビューできるファイルがありません",
        "files.and_more": "... 他 {n} ファイル",

        "settings.title": "⚙️ 設定",
        "mode.title": "🎨 透かしタイプ",
        "mode.text": "テキスト",
        "mode.logo": "ロゴ",

        "text.label": "✏️ テキスト",
        "text.placeholder": "© CyperMark",
        "text.font": "フォント",
        "text.font_size": "フォントサイズ",
        "text.color": "フォントの色",

        "stroke.title": "✏️ テキストの輪郭",
        "stroke.width": "幅",
        "stroke.color": "輪郭の色",

        "logo.title": "🖼️ ロゴ",
        "logo.select": "🖼️ PNGを選択",
        "logo.not_selected": "選択されていません",
        "logo.select_title": "ロゴ画像を選択",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "エラー：ロゴが選択されていません",

        "position.title": "📍 位置",
        "pos.top_left": "左上",
        "pos.top_center": "上中央",
        "pos.top_right": "右上",
        "pos.center": "中央",
        "pos.bottom_left": "左下",
        "pos.bottom_center": "下中央",
        "pos.bottom_right": "右下",
        "pos.tile": "タイル",

        "opacity": "不透明度",
        "rotation": "回転 (°)",

        "ai.title": "🤖 AI自動配置",
        "ai.label": "自由領域",

        "format.title": "💾 出力形式",
        "format.quality": "品質 (1-100)",

        "output.folder": "📥 出力フォルダ",
        "output.select": "📁 フォルダを選択",
        "output.not_selected": "選択されていません",

        "suffix.label": "🏷️ ファイル接尾辞",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 プリセットを保存",
        "preset.load": "📂 プリセットを読み込み",
        "preset.reset": "↺ リセット",
        "preset.save_title": "プリセットを保存",
        "preset.load_title": "プリセットを読み込み",
        "preset.saved": "プリセットを保存しました: {name}",
        "preset.loaded": "プリセットを読み込みました: {name}",
        "preset.reset_done": "設定をリセットしました",

        "preview.title": "🔍 プレビュー",
        "zoom.fit": "フィット",

        "status.ready": "準備完了",
        "status.processing": "🚀 処理中...",
        "status.completed": "✅ 完了！{n} ファイルを処理しました",
        "status.error": "エラー: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 開始",
        "btn.running": "⏳ 処理中...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ ご支援ありがとうございます！",

        "msg.no_files": "エラー：処理するファイルがありません",
        "msg.no_output": "エラー：出力フォルダが選択されていません",
        "msg.logo_required": "エラー：ロゴが選択されていません",
        "msg.preview_error": "プレビューエラー: {e}",
        "msg.startup": "CyperMark v2 準備完了。画像を追加してください。",
        "msg.logo_loaded": "ロゴ: {path}",
        "msg.files_added": "{n} ファイルを追加しました",
        "msg.folder_added": "フォルダを追加: {name} ({n} 画像)",
        "msg.output_selected": "出力フォルダ: {path}",
        "msg.saved_to": "✅ 完了！保存先: {path}",

        "color.pick_font": "フォントの色",
        "color.pick_stroke": "輪郭の色",

        "about.title": "ℹ️ 情報",
        "about.name": "⚡ CyperMark",
        "about.desc": "バッチ透かしツール",
        "about.subdesc": "AI画像保護",
        "about.version": "v2.0",
        "about.license": "ライセンス: MIT",
        "about.close": "閉じる",
    },

    # ═══════════════════════════════════════════════════════════
    #  한국어
    # ═══════════════════════════════════════════════════════════
    "ko": {
        "app.title": "CyperMark v2 — 배치 워터마크 도구",

        "files.title": "📁 파일",
        "files.add": "+ 파일 추가",
        "files.add_folder": "+ 폴더 추가",
        "files.clear": "✕ 목록 지우기",
        "files.none": "파일 없음",
        "files.count": "파일: {n}",
        "files.select_images": "이미지 선택",
        "files.select_folder": "이미지 폴더 선택",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "모든 파일",
        "files.cleared": "파일 목록이 지워졌습니다",
        "files.no_preview": "미리보기할 파일이 없습니다",
        "files.and_more": "... 외 {n}개 파일",

        "settings.title": "⚙️ 설정",
        "mode.title": "🎨 워터마크 유형",
        "mode.text": "텍스트",
        "mode.logo": "로고",

        "text.label": "✏️ 텍스트",
        "text.placeholder": "© CyperMark",
        "text.font": "글꼴",
        "text.font_size": "글꼴 크기",
        "text.color": "글꼴 색상",

        "stroke.title": "✏️ 텍스트 윤곽선",
        "stroke.width": "두께",
        "stroke.color": "윤곽선 색상",

        "logo.title": "🖼️ 로고",
        "logo.select": "🖼️ PNG 선택",
        "logo.not_selected": "선택되지 않음",
        "logo.select_title": "로고 이미지 선택",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "오류: 로고가 선택되지 않았습니다",

        "position.title": "📍 위치",
        "pos.top_left": "왼쪽 위",
        "pos.top_center": "위 중앙",
        "pos.top_right": "오른쪽 위",
        "pos.center": "중앙",
        "pos.bottom_left": "왼쪽 아래",
        "pos.bottom_center": "아래 중앙",
        "pos.bottom_right": "오른쪽 아래",
        "pos.tile": "타일",

        "opacity": "불투명도",
        "rotation": "회전 (°)",

        "ai.title": "🤖 AI 자동 배치",
        "ai.label": "자유 영역",

        "format.title": "💾 출력 형식",
        "format.quality": "품질 (1-100)",

        "output.folder": "📥 출력 폴더",
        "output.select": "📁 폴더 선택",
        "output.not_selected": "선택되지 않음",

        "suffix.label": "🏷️ 파일 접미사",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 프리셋 저장",
        "preset.load": "📂 프리셋 불러오기",
        "preset.reset": "↺ 초기화",
        "preset.save_title": "프리셋 저장",
        "preset.load_title": "프리셋 불러오기",
        "preset.saved": "프리셋 저장됨: {name}",
        "preset.loaded": "프리셋 불러옴: {name}",
        "preset.reset_done": "설정이 초기화되었습니다",

        "preview.title": "🔍 미리보기",
        "zoom.fit": "맞춤",

        "status.ready": "준비",
        "status.processing": "🚀 처리 중...",
        "status.completed": "✅ 완료! {n}개 파일 처리됨",
        "status.error": "오류: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 시작",
        "btn.running": "⏳ 처리 중...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ 지원해 주셔서 감사합니다!",

        "msg.no_files": "오류: 처리할 파일이 없습니다",
        "msg.no_output": "오류: 출력 폴더가 선택되지 않았습니다",
        "msg.logo_required": "오류: 로고가 선택되지 않았습니다",
        "msg.preview_error": "미리보기 오류: {e}",
        "msg.startup": "CyperMark v2 준비 완료. 이미지를 추가하세요.",
        "msg.logo_loaded": "로고: {path}",
        "msg.files_added": "{n}개 파일 추가됨",
        "msg.folder_added": "폴더 추가됨: {name} ({n}개 이미지)",
        "msg.output_selected": "출력 폴더: {path}",
        "msg.saved_to": "✅ 완료! 저장 위치: {path}",

        "color.pick_font": "글꼴 색상",
        "color.pick_stroke": "윤곽선 색상",

        "about.title": "ℹ️ 정보",
        "about.name": "⚡ CyperMark",
        "about.desc": "배치 워터마크 도구",
        "about.subdesc": "AI 이미지 보호",
        "about.version": "v2.0",
        "about.license": "라이선스: MIT",
        "about.close": "닫기",
    },

    # ═══════════════════════════════════════════════════════════
    #  العربية
    # ═══════════════════════════════════════════════════════════
    "ar": {
        "app.title": "CyperMark v2 — أداة العلامة المائية الدفعية",

        "files.title": "📁 الملفات",
        "files.add": "+ إضافة ملفات",
        "files.add_folder": "+ إضافة مجلد",
        "files.clear": "✕ مسح القائمة",
        "files.none": "لا توجد ملفات",
        "files.count": "الملفات: {n}",
        "files.select_images": "اختر الصور",
        "files.select_folder": "اختر مجلد الصور",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "جميع الملفات",
        "files.cleared": "تم مسح قائمة الملفات",
        "files.no_preview": "لا توجد ملفات للمعاينة",
        "files.and_more": "... و{n} ملفات أخرى",

        "settings.title": "⚙️ الإعدادات",
        "mode.title": "🎨 نوع العلامة المائية",
        "mode.text": "نص",
        "mode.logo": "شعار",

        "text.label": "✏️ النص",
        "text.placeholder": "© CyperMark",
        "text.font": "الخط",
        "text.font_size": "حجم الخط",
        "text.color": "لون الخط",

        "stroke.title": "✏️ حدود النص",
        "stroke.width": "العرض",
        "stroke.color": "لون الحدود",

        "logo.title": "🖼️ الشعار",
        "logo.select": "🖼️ اختر PNG",
        "logo.not_selected": "غير محدد",
        "logo.select_title": "اختر صورة الشعار",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "خطأ: لم يتم اختيار شعار",

        "position.title": "📍 الموضع",
        "pos.top_left": "أعلى اليسار",
        "pos.top_center": "أعلى الوسط",
        "pos.top_right": "أعلى اليمين",
        "pos.center": "الوسط",
        "pos.bottom_left": "أسفل اليسار",
        "pos.bottom_center": "أسفل الوسط",
        "pos.bottom_right": "أسفل اليمين",
        "pos.tile": "بلاط",

        "opacity": "الشفافية",
        "rotation": "الدوران (°)",

        "ai.title": "🤖 تحديد الموضع بالذكاء الاصطناعي",
        "ai.label": "منطقة حرة",

        "format.title": "💾 تنسيق الإخراج",
        "format.quality": "الجودة (1-100)",

        "output.folder": "📥 مجلد الإخراج",
        "output.select": "📁 اختر مجلد",
        "output.not_selected": "غير محدد",

        "suffix.label": "🏷️ لاحقة الملف",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 حفظ الإعداد المسبق",
        "preset.load": "📂 تحميل الإعداد المسبق",
        "preset.reset": "↺ إعادة تعيين",
        "preset.save_title": "حفظ الإعداد المسبق",
        "preset.load_title": "تحميل الإعداد المسبق",
        "preset.saved": "تم حفظ الإعداد المسبق: {name}",
        "preset.loaded": "تم تحميل الإعداد المسبق: {name}",
        "preset.reset_done": "تم إعادة تعيين الإعدادات",

        "preview.title": "🔍 معاينة",
        "zoom.fit": "ملاءمة",

        "status.ready": "جاهز",
        "status.processing": "🚀 جاري المعالجة...",
        "status.completed": "✅ اكتمل! تمت معالجة {n} ملف",
        "status.error": "خطأ: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 بدء",
        "btn.running": "⏳ جاري المعالجة...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ شكراً لدعمك!",

        "msg.no_files": "خطأ: لا توجد ملفات للمعالجة",
        "msg.no_output": "خطأ: لم يتم اختيار مجلد الإخراج",
        "msg.logo_required": "خطأ: لم يتم اختيار شعار",
        "msg.preview_error": "خطأ في المعاينة: {e}",
        "msg.startup": "CyperMark v2 جاهز. أضف الصور للبدء.",
        "msg.logo_loaded": "الشعار: {path}",
        "msg.files_added": "تمت إضافة {n} ملفات",
        "msg.folder_added": "تمت إضافة المجلد: {name} ({n} صور)",
        "msg.output_selected": "مجلد الإخراج: {path}",
        "msg.saved_to": "✅ اكتمل! تم الحفظ في: {path}",

        "color.pick_font": "لون الخط",
        "color.pick_stroke": "لون الحدود",

        "about.title": "ℹ️ حول",
        "about.name": "⚡ CyperMark",
        "about.desc": "أداة العلامة المائية الدفعية",
        "about.subdesc": "حماية الصور بالذكاء الاصطناعي",
        "about.version": "v2.0",
        "about.license": "الترخيص: MIT",
        "about.close": "إغلاق",
    },

    # ═══════════════════════════════════════════════════════════
    #  TÜRKÇE
    # ═══════════════════════════════════════════════════════════
    "tr": {
        "app.title": "CyperMark v2 — Toplu Filigran Aracı",

        "files.title": "📁 Dosyalar",
        "files.add": "+ Dosya Ekle",
        "files.add_folder": "+ Klasör Ekle",
        "files.clear": "✕ Listeyi Temizle",
        "files.none": "Dosya yok",
        "files.count": "Dosya: {n}",
        "files.select_images": "Görselleri seç",
        "files.select_folder": "Görsel klasörünü seç",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Tüm dosyalar",
        "files.cleared": "Dosya listesi temizlendi",
        "files.no_preview": "Önizleme için dosya yok",
        "files.and_more": "... ve {n} dosya daha",

        "settings.title": "⚙️ Ayarlar",
        "mode.title": "🎨 Filigran Türü",
        "mode.text": "Metin",
        "mode.logo": "Logo",

        "text.label": "✏️ Metin",
        "text.placeholder": "© CyperMark",
        "text.font": "Yazı tipi",
        "text.font_size": "Yazı boyutu",
        "text.color": "Yazı rengi",

        "stroke.title": "✏️ Metin Anahattı",
        "stroke.width": "Kalınlık",
        "stroke.color": "Anahat rengi",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ PNG Seç",
        "logo.not_selected": "Seçilmedi",
        "logo.select_title": "Logo görselini seç",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Hata: logo seçilmedi",

        "position.title": "📍 Konum",
        "pos.top_left": "Sol üst",
        "pos.top_center": "Üst orta",
        "pos.top_right": "Sağ üst",
        "pos.center": "Merkez",
        "pos.bottom_left": "Sol alt",
        "pos.bottom_center": "Alt orta",
        "pos.bottom_right": "Sağ alt",
        "pos.tile": "Döşe",

        "opacity": "Opaklık",
        "rotation": "Dönüş (°)",

        "ai.title": "🤖 AI Otomatik Yerleşim",
        "ai.label": "Serbest alan",

        "format.title": "💾 Çıktı Formatı",
        "format.quality": "Kalite (1-100)",

        "output.folder": "📥 Çıktı Klasörü",
        "output.select": "📁 Klasör Seç",
        "output.not_selected": "Seçilmedi",

        "suffix.label": "🏷️ Dosya Soneki",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Ön Ayarı Kaydet",
        "preset.load": "📂 Ön Ayarı Yükle",
        "preset.reset": "↺ Sıfırla",
        "preset.save_title": "Ön Ayarı Kaydet",
        "preset.load_title": "Ön Ayarı Yükle",
        "preset.saved": "Ön ayar kaydedildi: {name}",
        "preset.loaded": "Ön ayar yüklendi: {name}",
        "preset.reset_done": "Ayarlar sıfırlandı",

        "preview.title": "🔍 Önizleme",
        "zoom.fit": "Sığdır",

        "status.ready": "Hazır",
        "status.processing": "🚀 İşleniyor...",
        "status.completed": "✅ Tamamlandı! {n} dosya işlendi",
        "status.error": "Hata: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 BAŞLAT",
        "btn.running": "⏳ İŞLENİYOR...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Desteğiniz için teşekkürler!",

        "msg.no_files": "Hata: işlenecek dosya yok",
        "msg.no_output": "Hata: çıktı klasörü seçilmedi",
        "msg.logo_required": "Hata: logo seçilmedi",
        "msg.preview_error": "Önizleme hatası: {e}",
        "msg.startup": "CyperMark v2 hazır. Görsel ekleyin.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} dosya eklendi",
        "msg.folder_added": "Klasör eklendi: {name} ({n} görsel)",
        "msg.output_selected": "Çıktı klasörü: {path}",
        "msg.saved_to": "✅ Tamamlandı! Kaydedildi: {path}",

        "color.pick_font": "Yazı rengi",
        "color.pick_stroke": "Anahat rengi",

        "about.title": "ℹ️ Hakkında",
        "about.name": "⚡ CyperMark",
        "about.desc": "Toplu filigran aracı",
        "about.subdesc": "AI destekli görsel koruma",
        "about.version": "v2.0",
        "about.license": "Lisans: MIT",
        "about.close": "Kapat",
    },

    # ═══════════════════════════════════════════════════════════
    #  POLSKI
    # ═══════════════════════════════════════════════════════════
    "pl": {
        "app.title": "CyperMark v2 — Znak wodny wsadowy",

        "files.title": "📁 Pliki",
        "files.add": "+ Dodaj pliki",
        "files.add_folder": "+ Dodaj folder",
        "files.clear": "✕ Wyczyść listę",
        "files.none": "Brak plików",
        "files.count": "Pliki: {n}",
        "files.select_images": "Wybierz obrazy",
        "files.select_folder": "Wybierz folder z obrazami",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Wszystkie pliki",
        "files.cleared": "Lista plików wyczyszczona",
        "files.no_preview": "Brak plików do podglądu",
        "files.and_more": "... i {n} więcej plików",

        "settings.title": "⚙️ Ustawienia",
        "mode.title": "🎨 Typ znaku wodnego",
        "mode.text": "Tekst",
        "mode.logo": "Logo",

        "text.label": "✏️ Tekst",
        "text.placeholder": "© CyperMark",
        "text.font": "Czcionka",
        "text.font_size": "Rozmiar czcionki",
        "text.color": "Kolor czcionki",

        "stroke.title": "✏️ Kontur tekstu",
        "stroke.width": "Grubość",
        "stroke.color": "Kolor konturu",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ Wybierz PNG",
        "logo.not_selected": "Nie wybrano",
        "logo.select_title": "Wybierz obraz logo",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Błąd: nie wybrano logo",

        "position.title": "📍 Pozycja",
        "pos.top_left": "Lewy górny",
        "pos.top_center": "Góra środek",
        "pos.top_right": "Prawy górny",
        "pos.center": "Środek",
        "pos.bottom_left": "Lewy dolny",
        "pos.bottom_center": "Dół środek",
        "pos.bottom_right": "Prawy dolny",
        "pos.tile": "Kafelki",

        "opacity": "Nieprzezroczystość",
        "rotation": "Obrót (°)",

        "ai.title": "🤖 AI Auto-Rozmieszczenie",
        "ai.label": "Wolny obszar",

        "format.title": "💾 Format wyjściowy",
        "format.quality": "Jakość (1-100)",

        "output.folder": "📥 Folder wyjściowy",
        "output.select": "📁 Wybierz folder",
        "output.not_selected": "Nie wybrano",

        "suffix.label": "🏷️ Przyrostek pliku",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Zapisz preset",
        "preset.load": "📂 Wczytaj preset",
        "preset.reset": "↺ Resetuj",
        "preset.save_title": "Zapisz preset",
        "preset.load_title": "Wczytaj preset",
        "preset.saved": "Preset zapisany: {name}",
        "preset.loaded": "Preset wczytany: {name}",
        "preset.reset_done": "Ustawienia zresetowane",

        "preview.title": "🔍 Podgląd",
        "zoom.fit": "Dopasuj",

        "status.ready": "Gotowy",
        "status.processing": "🚀 Przetwarzanie...",
        "status.completed": "✅ Gotowe! Przetworzono {n} plików",
        "status.error": "Błąd: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 START",
        "btn.running": "⏳ PRZETWARZANIE...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Dziękujemy za wsparcie!",

        "msg.no_files": "Błąd: brak plików do przetworzenia",
        "msg.no_output": "Błąd: nie wybrano folderu wyjściowego",
        "msg.logo_required": "Błąd: nie wybrano logo",
        "msg.preview_error": "Błąd podglądu: {e}",
        "msg.startup": "CyperMark v2 gotowy. Dodaj obrazy.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "Dodano {n} plików",
        "msg.folder_added": "Dodano folder: {name} ({n} obrazów)",
        "msg.output_selected": "Folder wyjściowy: {path}",
        "msg.saved_to": "✅ Gotowe! Zapísano w: {path}",

        "color.pick_font": "Kolor czcionki",
        "color.pick_stroke": "Kolor konturu",

        "about.title": "ℹ️ O programie",
        "about.name": "⚡ CyperMark",
        "about.desc": "Znak wodny wsadowy",
        "about.subdesc": "Ochrona obrazów z AI",
        "about.version": "v2.0",
        "about.license": "Licencja: MIT",
        "about.close": "Zamknij",
    },

    # ═══════════════════════════════════════════════════════════
    #  NEDERLANDS
    # ═══════════════════════════════════════════════════════════
    "nl": {
        "app.title": "CyperMark v2 — Batch Watermerk Tool",

        "files.title": "📁 Bestanden",
        "files.add": "+ Bestanden toevoegen",
        "files.add_folder": "+ Map toevoegen",
        "files.clear": "✕ Lijst leegmaken",
        "files.none": "Geen bestanden",
        "files.count": "Bestanden: {n}",
        "files.select_images": "Afbeeldingen selecteren",
        "files.select_folder": "Map met afbeeldingen selecteren",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Alle bestanden",
        "files.cleared": "Bestandenlijst gewist",
        "files.no_preview": "Geen bestanden voor voorbeeld",
        "files.and_more": "... en nog {n} bestanden",

        "settings.title": "⚙️ Instellingen",
        "mode.title": "🎨 Watermerk Type",
        "mode.text": "Tekst",
        "mode.logo": "Logo",

        "text.label": "✏️ Tekst",
        "text.placeholder": "© CyperMark",
        "text.font": "Lettertype",
        "text.font_size": "Lettergrootte",
        "text.color": "Tekstkleur",

        "stroke.title": "✏️ Tekstomtrek",
        "stroke.width": "Dikte",
        "stroke.color": "Omtrekkleur",

        "logo.title": "🖼️ Logo",
        "logo.select": "🖼️ PNG selecteren",
        "logo.not_selected": "Niet geselecteerd",
        "logo.select_title": "Logo afbeelding selecteren",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Fout: geen logo geselecteerd",

        "position.title": "📍 Positie",
        "pos.top_left": "Linksboven",
        "pos.top_center": "Boven midden",
        "pos.top_right": "Rechtsboven",
        "pos.center": "Midden",
        "pos.bottom_left": "Linksonder",
        "pos.bottom_center": "Onder midden",
        "pos.bottom_right": "Rechtsonder",
        "pos.tile": "Tegel",

        "opacity": "Dekking",
        "rotation": "Rotatie (°)",

        "ai.title": "🤖 AI Auto-Platasing",
        "ai.label": "Vrij gebied",

        "format.title": "💾 Uitvoerformaat",
        "format.quality": "Kwaliteit (1-100)",

        "output.folder": "📥 Uitvoermap",
        "output.select": "📁 Map selecteren",
        "output.not_selected": "Niet geselecteerd",

        "suffix.label": "🏷️ Bestandssuffix",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Voorinstelling opslaan",
        "preset.load": "📂 Voorinstelling laden",
        "preset.reset": "↺ Resetten",
        "preset.save_title": "Voorinstelling opslaan",
        "preset.load_title": "Voorinstelling laden",
        "preset.saved": "Voorinstelling opgeslagen: {name}",
        "preset.loaded": "Voorinstelling geladen: {name}",
        "preset.reset_done": "Instellingen gereset",

        "preview.title": "🔍 Voorbeeld",
        "zoom.fit": "Passend",

        "status.ready": "Gereed",
        "status.processing": "🚀 Bezig met verwerken...",
        "status.completed": "✅ Klaar! {n} bestanden verwerkt",
        "status.error": "Fout: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 START",
        "btn.running": "⏳ BEZIG...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Bedankt voor je steun!",

        "msg.no_files": "Fout: geen bestanden om te verwerken",
        "msg.no_output": "Fout: geen uitvoermap geselecteerd",
        "msg.logo_required": "Fout: geen logo geselecteerd",
        "msg.preview_error": "Voorbeeldfout: {e}",
        "msg.startup": "CyperMark v2 gereed. Voeg afbeeldingen toe.",
        "msg.logo_loaded": "Logo: {path}",
        "msg.files_added": "{n} bestanden toegevoegd",
        "msg.folder_added": "Map toegevoegd: {name} ({n} afbeeldingen)",
        "msg.output_selected": "Uitvoermap: {path}",
        "msg.saved_to": "✅ Klaar! Opgeslagen in: {path}",

        "color.pick_font": "Tekstkleur",
        "color.pick_stroke": "Omtrekkleur",

        "about.title": "ℹ️ Over",
        "about.name": "⚡ CyperMark",
        "about.desc": "Batch watermerk tool",
        "about.subdesc": "AI beeldbeveiliging",
        "about.version": "v2.0",
        "about.license": "Licentie: MIT",
        "about.close": "Sluiten",
    },

    # ═══════════════════════════════════════════════════════════
    #  SVENSKA
    # ═══════════════════════════════════════════════════════════
    "sv": {
        "app.title": "CyperMark v2 — Batch-vattenmärkesverktyg",

        "files.title": "📁 Filer",
        "files.add": "+ Lägg till filer",
        "files.add_folder": "+ Lägg till mapp",
        "files.clear": "✕ Rensa listan",
        "files.none": "Inga filer",
        "files.count": "Filer: {n}",
        "files.select_images": "Välj bilder",
        "files.select_folder": "Välj mapp med bilder",
        "files.all_formats": "*.png *.jpg *.jpeg *.webp *.bmp *.tiff",
        "files.all_files": "Alla filer",
        "files.cleared": "Fillistan rensad",
        "files.no_preview": "Inga filer för förhandsgranskning",
        "files.and_more": "... och {n} fler filer",

        "settings.title": "⚙️ Inställningar",
        "mode.title": "🎨 Vattenmärkestyp",
        "mode.text": "Text",
        "mode.logo": "Logotyp",

        "text.label": "✏️ Text",
        "text.placeholder": "© CyperMark",
        "text.font": "Typsnitt",
        "text.font_size": "Teckenstorlek",
        "text.color": "Textfärg",

        "stroke.title": "✏️ Textkontur",
        "stroke.width": "Bredd",
        "stroke.color": "Konturfärg",

        "logo.title": "🖼️ Logotyp",
        "logo.select": "🖼️ Välj PNG",
        "logo.not_selected": "Inte vald",
        "logo.select_title": "Välj logotypbild",
        "logo.format_png": "PNG",
        "logo.format_jpeg": "JPEG",
        "logo.format_webp": "WEBP",
        "logo.format_bmp": "BMP",
        "logo.format_tiff": "TIFF",
        "logo.error_required": "Fel: ingen logotyp vald",

        "position.title": "📍 Position",
        "pos.top_left": "Övre vänster",
        "pos.top_center": "Övre centrum",
        "pos.top_right": "Övre höger",
        "pos.center": "Centrum",
        "pos.bottom_left": "Nedre vänster",
        "pos.bottom_center": "Nedre centrum",
        "pos.bottom_right": "Nedre höger",
        "pos.tile": "Kakel",

        "opacity": "Opacitet",
        "rotation": "Rotation (°)",

        "ai.title": "🤖 AI Auto-Placering",
        "ai.label": "Fritt område",

        "format.title": "💾 Utdataformat",
        "format.quality": "Kvalitet (1-100)",

        "output.folder": "📥 Utdatamapp",
        "output.select": "📁 Välj mapp",
        "output.not_selected": "Inte vald",

        "suffix.label": "🏷️ Filändelse",
        "suffix.placeholder": "_watermarked",

        "preset.save": "💾 Spara förinställning",
        "preset.load": "📂 Ladda förinställning",
        "preset.reset": "↺ Återställ",
        "preset.save_title": "Spara förinställning",
        "preset.load_title": "Ladda förinställning",
        "preset.saved": "Förinställning sparad: {name}",
        "preset.loaded": "Förinställning laddad: {name}",
        "preset.reset_done": "Inställningarna återställda",

        "preview.title": "🔍 Förhandsgranskning",
        "zoom.fit": "Anpassa",

        "status.ready": "Redo",
        "status.processing": "🚀 Bearbetar...",
        "status.completed": "✅ Klar! {n} filer bearbetade",
        "status.error": "Fel: {msg}",
        "status.progress": "{cur}/{total}",
        "btn.start": "🚀 START",
        "btn.running": "⏳ BEARBETAR...",
        "btn.donate": "❤️",
        "donate.thanks": "❤️ Tack för ditt stöd!",

        "msg.no_files": "Fel: inga filer att bearbeta",
        "msg.no_output": "Fel: ingen utdatamapp vald",
        "msg.logo_required": "Fel: ingen logotyp vald",
        "msg.preview_error": "Förhandsgranskningsfel: {e}",
        "msg.startup": "CyperMark v2 redo. Lägg till bilder.",
        "msg.logo_loaded": "Logotyp: {path}",
        "msg.files_added": "{n} filer tillagda",
        "msg.folder_added": "Mapp tillagd: {name} ({n} bilder)",
        "msg.output_selected": "Utdatamapp: {path}",
        "msg.saved_to": "✅ Klar! Sparat i: {path}",

        "color.pick_font": "Textfärg",
        "color.pick_stroke": "Konturfärg",

        "about.title": "ℹ️ Om",
        "about.name": "⚡ CyperMark",
        "about.desc": "Batch-vattenmärkesverktyg",
        "about.subdesc": "AI-bildskydd",
        "about.version": "v2.0",
        "about.license": "Licens: MIT",
        "about.close": "Stäng",
    },
}

# ─── Язык по умолчанию ────────────────────────────────────────
DEFAULT_LANG = "ru"


def get_language(lang_code: str) -> dict[str, str]:
    """Возвращает словарь переводов для языка."""
    return LANGUAGES.get(lang_code, LANGUAGES[DEFAULT_LANG])
